import { environment } from "src/environments/environment";

export class Banks {
  agribank: string = "#005a3c";
  acb: string = "";
  vietcombank: string = "#74b142";
  techcombank: string = "";
  bidv: string = "#213a99";
  cb: string = "#fdba13";
  msb: string = "#ea6d21";
  mb: string = "";
  vietinbank: string = "#cf0228";
  scb: string = "#c01224";
  oceanbank: string = "#8aced8";
  bacabank: string = "#c88b02";
  maritimebank: string = "#e51b23";
  nam: string = "#f8da01";
  ncb: string = "#004a94";
  dongabank: string = "#015498";
  vib: string = "#014f94";
  shb: string = "#f47c35";
  ocb: string = "#008843";
  eximbank: string = "#0069ac";
  baoviet: string = "#0075c0";
}

export class Logos {
  agribank: string = "/assets/images/agribank.jpg";
  acb: string = "/assets/images/acb.png";
  vietcombank: string = "/assets/images/vietcombank.png";
  techcombank: string = "/assets/images/techcombank.png";
  bidv: string = "/assets/images/bidv.png";
  cb: string = "/assets/images/cb.jpg";
  msb: string = "/assets/images/msb.jpg";
  mbb: string = "/assets/images/mbb.jpg";
  vietinbank: string = "/assets/images/vietinbank.png";
  scb: string = "/assets/images/scb.jpg";
  oceanbank: string = "/assets/images/oceanbank.jpg";
  bacabank: string = "/assets/images/bacabank.png";
  nam: string = "/assets/images/nama.jpg";
  ncb: string = "/assets/images/ncb.jpg";
  dongabank: string = "/assets/images/dongabank.jpg";
  vib: string = "/assets/images/vib.png";
  shb: string = "/assets/images/shb.png";
  ocb: string = "/assets/images/ocb.png";
  eximbank: string = "/assets/images/eximbank.jpg";
  baovietbank: string = "/assets/images/baovietbank.jpg";
  gpbank: string = "/assets/images/gpbank.png";
  abbank: string = "/assets/images/abbank.jpg";
  hdbank: string = "/assets/images/hdbank.jpg";
  kienlongbank: string = "/assets/images/kienlongbank.jpg";
  lienvietpostbank: string = "/assets/images/lienvietpostbank.jpg";
  sacombank: string = "/assets/images/sacombank.png";
  saigonbank: string = "/assets/images/saigonbank.png";
  tpbank: string = "/assets/images/tpbank.png";
  vietbank: string = "/assets/images/vietbank.png";
  vietabank: string = "/assets/images/vietabank.png";
  vietcapitalbank: string = "/assets/images/vietcapital.jpg";
  vpbank: string = "/assets/images/vpbank.jpg";
  anz: string = "/assets/images/anz.png";
  hsbc: string = "/assets/images/hsbc.png";
  standard: string = "/assets/images/standard.jpg";
  pgbank: string = "/assets/images/pgb.png";
  seabank: string = "/assets/images/seabank.png";
  ivb: string = "/assets/images/ivb.jpg";
  pvcombank: string = "/assets/images/pvc.png";
}
